version : "3.8"
name : 'spring-boot-microservices-rabbitmq'
services:
   catalog-db:
     image : postgres:16-alpine
     container_name: catalog-db
     environment:
       - POSTGRES_USER=naingaungzaw
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=catalog
     ports:
       - "15432:5432"
     healthcheck:
       test: [ "CMD", "pg_isready", "-U", "naingaungzaw", "-d", "catalog" ]
       interval: 10s
       timeout: 5s
       retries: 5
     deploy:
       resources:
         limits:
           memory: 500m

   order-db:
     image: postgres:16-alpine
     container_name: order-db
     environment:
       - POSTGRES_USER=naingaungzaw
       - POSTGRES_PASSWORD=password
       - POSTGRES_DB=order
     ports:
       - "25432:5432"
     healthcheck:
       test: ["CMD","pg_isready","-U","naingaungzaw","-d","order"]
       interval: 10s
       timeout: 5s
       retries: 5
     deploy:
       resources:
         limits:
           memory: 500m

   bookstore-rabbitmq:
     image: rabbitmq:3.12.11-management
     container_name: bookstore-rabbitmq
     environment:
       - RABBITMQ_DEFAULT_USER=guest
       - RABBITMQ_DEFAULT_PASS=guest
     ports:
       - "5672:5672" #amqp port
       - "15672:15672" #web ui port
     healthcheck:
       test: rabbitmq-diagnostics check_port_connectivity
       interval: 30s
       timeout: 5s
       retries: 5
     deploy:
       resources:
         limits:
           memory: 500m


