name: Catalog-Service

on:
  push:
    paths:
      - catalog-service/**
    branches:
      - '**'
jobs:
  build:
    name : Build
    runs-on: ubuntu-latest
    env:
      working-directory : ./catalog-service
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Clean up action
      - uses: actions/checkout@v4

      - name: Setp up java 21
        uses: actions/setup-java@v4
        with:
          java-version : '21'
          distribution : 'temurin'
          cache: 'maven'

      - name : Build with maven
        run : ./mvnw -ntp verify


#     login and publish to docker hub only on main branch
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build and publish docker image
        run:
          ./mvnw -pl catalog-service spring-boot:build-image -DskipTests
          docker push ${{secrets.DOCKERHUB_USERNAME}}/bookstore-catalog-service


