name: Order-Service

on:
  push:
    paths:
      - order-service/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: Ubuntu-latest
    env:
      working-directory: ./order-service
      DOCKER_IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME}}/bookstore-order-service
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - name: Clean up
        uses: actions/checkout@v4

      - name: Set up Java@21
        uses: actions/setup-java@4
        with:
          java-version: '21'
          distribution: 'termuin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw -ntp verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

      - name: Build and Publish to Docker Hub
        run: |
          ./mvnw -pl order-service spring-boot:build-image -DskipTests
          docker push ${{secrets.DOCKERHUB_USERNAME}}/bookstore/order-service

